#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge $HOME/.Xresources

redshift -v -b 0.9:0.8 -t 6000K:3000K -l "48.08:-89.38" &

xset s off
xset -dpms

# for Java apps showing up blank
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

# http://www.reddit.com/r/unixporn/comments/1tsox7/bspwm_cursor_is_an_x/
# Use normal cursor
xsetroot -cursor_name left_ptr

setxkbmap -option ctrl:nocaps

setxkbmap -layout en_US,ru
setxkbmap -option grp:toggle

# Disable inertial scrolling [RUKH-7]
xinput --set-prop --type=float "SynPS/2 Synaptics TouchPad" "Synaptics Coasting Speed" 0 0
# Disable touchpad while typing [SYS-52]
syndaemon -i 1 -t -k &

synclient TapButton1=1 TapButton2=3 TapButton3=2

sxhkd &
#exec /usr/bin/bspwm 2>&1 >> /tmp/bsp.log
exec bspwm
