#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge $HOME/.Xresources

#xrandr --output LVDS1 --off
#xrandr --output VGA1 --off
#xrandr --output DP2 --off
#xrandr --output HDMI1 --off

# latest two setups 2015-05-22
# TODO this if condition is not working correctly
if false ; then #`xrandr | grep 'HDMI1 connected'` ; then
	echo "Starting with monitors" >> /tmp/xinit
	# being weird after update on 2015-10-16, not init'ing HDMI1 and sleep fixes it
	#sleep 30
	xrandr >> /tmp/xinit
	# Two screens at desk (workstation)
	#xrandr --output HDMI1 --primary --auto
	#xrandr --output DP2 --auto --left-of HDMI1 --pos 1080x520 --rotate left
	xrandr --output LVDS1 --off
	#xrandr --output DP2 --mode 2560x1080
	#sleep 20
	xrandr >> /tmp/xinit
	xrandr --output DP2 --mode 2560x1080
else
	echo "Using laptop screen" >> /tmp/xinit
	# Laptop screen only (on the go)
	#xrandr --output LVDS1 --primary --mode 1366x768
	#xrandr --output HDMI1 --auto --right-of LVDS1
fi

redshift &

xset s off
xset -dpms

# for the kensington mac mouse after mine broke 2015-04-19
#xset m 3/1 0

setxkbmap -option ctrl:nocaps

# Disable inertial scrolling [RUKH-7]
xinput --set-prop --type=float "SynPS/2 Synaptics TouchPad" "Synaptics Coasting Speed" 0 0
# Disable touchpad while typing [SYS-52]
syndaemon -i 1 -t -k

sxhkd &
# Conky places a significant load on Xorg, not sure why
#conky &
xmobar &
#st &
#exec /home/jbalint/sw/bspwm/bspwm 2>&1 >> /tmp/bsp.log
#exec /usr/bin/bspwm 2>&1 >> /tmp/bsp.log
exec bspwm
